### PR TITLE
feat(formula): align to template formula; basic ci support

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [x] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES

### Describe the changes you're proposing

This PR aligns to templates formula.  

Travis jobs are disabled because we cannot use oracle URL for downloads (login), so until some staging area is made available we cannot test effectively.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Tested manually on MacOS/Linux.  Here is Archlinux trace
```
local:
----------
          ID: sqldeveloper-package-archive-clean-file-absent
    Function: file.absent
        Name: /usr/local/oracle/12_2/sqldeveloper
      Result: True
     Comment: Removed directory /usr/local/oracle/12_2/sqldeveloper
     Started: 14:31:38.587623
    Duration: 148.457 ms
     Changes:   
              ----------
              removed:
                  /usr/local/oracle/12_2/sqldeveloper
----------
          ID: sqldeveloper-package-archive-clean-file-absent
    Function: file.absent
        Name: /usr/local/bin/sqldeveloper
      Result: True
     Comment: Removed file /usr/local/bin/sqldeveloper
     Started: 14:31:38.736290
    Duration: 0.74 ms
     Changes:   
              ----------
              removed:
                  /usr/local/bin/sqldeveloper
----------
          ID: sqldeveloper-config-clean-file-absent
    Function: file.absent
        Name: /tmp/dummy_list_item
      Result: True
     Comment: File /tmp/dummy_list_item is not present
     Started: 14:31:38.737347
    Duration: 0.438 ms
     Changes:   
----------
          ID: sqldeveloper-config-clean-file-absent
    Function: file.absent
        Name: /home/undefined_user/.sqldeveloper
      Result: True
     Comment: Removed directory /home/undefined_user/.sqldeveloper
     Started: 14:31:38.737995
    Duration: 0.83 ms
     Changes:   
              ----------
              removed:
                  /home/undefined_user/.sqldeveloper
----------
          ID: sqldeveloper-config-clean-file-absent
    Function: file.absent
        Name: /etc/default/sqldeveloper.sh
      Result: True
     Comment: File /etc/default/sqldeveloper.sh is not present
     Started: 14:31:38.739077
    Duration: 0.347 ms
     Changes:   
----------
          ID: sqldeveloper-config-clean-file-absent
    Function: file.absent
        Name: /usr/share/applications/sqldeveloper.desktop
      Result: True
     Comment: Removed file /usr/share/applications/sqldeveloper.desktop
     Started: 14:31:38.739645
    Duration: 0.373 ms
     Changes:   
              ----------
              removed:
                  /usr/share/applications/sqldeveloper.desktop
----------
          ID: sqldeveloper-linuxenv-alternatives-clean-unapplicable
    Function: test.show_notification
      Result: True
     Comment: Linux alternatives are turned off (sqldeveloper.linux.altpriority=0),
              or not applicable on Arch OS.
     Started: 14:31:38.740574
    Duration: 0.541 ms
     Changes:   
----------
          ID: sqldeveloper-package-archive-install-prepare
    Function: pkg.installed
        Name: curl
      Result: True
     Comment: All specified packages are already installed
     Started: 14:31:39.225645
    Duration: 42.47 ms
     Changes:   
----------
          ID: sqldeveloper-package-archive-install-prepare
    Function: pkg.installed
        Name: gzip
      Result: True
     Comment: All specified packages are already installed
     Started: 14:31:39.268346
    Duration: 28.057 ms
     Changes:   
----------
          ID: sqldeveloper-package-archive-install-prepare
    Function: file.directory
        Name: /usr/local/oracle/12_2
      Result: True
     Comment: The directory /usr/local/oracle/12_2 is in the correct state
     Started: 14:31:39.296565
    Duration: 1.576 ms
     Changes:   
----------
          ID: sqldeveloper-package-archive-install-sqldeveloper
    Function: archive.extracted
        Name: /usr/local/oracle/12_2
      Result: True
     Comment: http://arch.overstock.com/downloads/devtools/oracle//sqldeveloper-17.3.1.279.0537-no-jre.zip extracted to /usr/local/oracle/12_2/, due to absence of one or more files/dirs
     Started: 14:31:39.300065
    Duration: 7036.236 ms
     Changes:   
              ----------
              extracted_files:
                  - sqldeveloper/configuration/bundles.info
                  - sqldeveloper/configuration/oracle.datamodeler.bundles.info
                  - sqldeveloper/configuration/oracle.ide.sqldev.bundles.info
<<< CUT >>>
                  - sqldeveloper/dataminer/scripts/odmr_engine_text_sec_body.plb
                  - List trimmed after 100 files.
----------
          ID: sqldeveloper-archive-install-file-symlink-sqldeveloper
    Function: file.symlink
        Name: /usr/local/bin/sqldeveloper
      Result: True
     Comment: Created new symlink /usr/local/bin/sqldeveloper -> /usr/local/oracle/12_2/sqldeveloper//sqldeveloper.sh
     Started: 14:31:46.336466
    Duration: 547.331 ms
     Changes:   
              ----------
              new:
                  /usr/local/bin/sqldeveloper
----------
          ID: sqldeveloper-config-file-file-managed-desktop-shortcut_file
    Function: file.managed
        Name: /usr/share/applications/sqldeveloper.desktop
      Result: True
     Comment: File /usr/share/applications/sqldeveloper.desktop updated
     Started: 14:31:46.886625
    Duration: 870.436 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
              user:
                  undefined_user
----------
          ID: sqldeveloper-config-file-managed-product_file
    Function: file.managed
        Name: /home/undefined_user/.sqldeveloper/12_2/product.conf
      Result: True
     Comment: File /home/undefined_user/.sqldeveloper/12_2/product.conf updated
     Started: 14:31:47.757354
    Duration: 2.72 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0640
              user:
                  undefined_user
----------
          ID: -config-file-managed-prefs_file
    Function: cmd.run
        Name: curl -L -o /home/undefined_user/connections-with-password.xml None
      Result: True
     Comment: onlyif condition is false
     Started: 14:31:47.760288
    Duration: 28.108 ms
     Changes:   
----------
          ID: sqldeveloper-linuxenv-alternatives-install-unapplicable
    Function: file.symlink
        Name: /opt/sqldeveloper
      Result: True
     Comment: Symlink /opt/sqldeveloper is present and owned by root:root
     Started: 14:31:47.788713
    Duration: 14.584 ms
     Changes:   
----------
          ID: sqldeveloper-linuxenv-alternatives-install-unapplicable
    Function: test.show_notification
      Result: True
     Comment: Linux alternatives are turned off (sqldeveloper.linux.altpriority=0),
              or not applicable on Arch OS.
     Started: 14:31:47.803510
    Duration: 0.336 ms
     Changes:   

Summary for local
-------------
Succeeded: 17 (changed=8)
Failed:     0
```

**Comment by noelmcloughlin** [comment]
Fixed conflicts with the master.

**Comment by myii** [comment]
@noelmcloughlin All of the instances are failing in Travis.

**Comment by noelmcloughlin** [comment]
I need to reopen the PR as having troubles fixing this and resolving resulting conflicts

**Pull request closed without merging**
